### ISSUE TITLE
Rest pattern in hlist/coprod macros

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#100]
I think it can be useful to have a syntax for representing "the rest of the list" in `hlist!`, `Coprod!`, etc

 It is tempting to use `..rest` for this syntax but that would be ambiguous with otherwise perfectly valid patterns and expressions.  I suggest `/rest` as the syntax:

```rust
// Trait for HLists with at least two elements
pub trait AtLeastTwo { }

impl<A, B, Rest> AtLeastTwo for Hlist!(A, B, /Rest) { }
```

```rust
let hlist_pat![head, /tail] = list;

assert_eq!(list, hlist![head, /tail]);
```

I can basically just copy over [what I did here](https://github.com/ExpHP/funky/blob/master/src/macros.rs) if there is interest.

**Comment by Centril** [comment]
Seems like an interesting idea! I'd like to think over some bikeshed tomorrow though.

**Comment by Centril** [comment]
Could we use the `...` (note triple `.`) syntax now that `..=` will be used in its stead?
It seems to me more legible than `/`, even if two tokens longer.

It would also be quite neat to be able to say:
```rust
let hlist_pat![A, B, ...] = hlist![A, B, C, D];
```

for "I don't care about the rest, please drop it".

**Comment by Centril** [comment]
So I'm mainly in favor of `...` or some similar syntax cause it associates nicely with FRU, tuple pattern syntax, etc. If I would see `hlist_pat![a, b, ...]` I would immediately understand what is happening here, but not so with `hlist_pat![a, b, /_]`, so I'd have to look up the latter. I do think we should optimize for reading and not writing here, and so error messages should be secondary.

Some other variants to consider?

```rust
hlist_pat![a, b, ++ hlist_pat![..]] // Append
hlist_pat![a, b, << hlist_pat![..]] // Shift in
```

**Comment by ExpHP** [comment]
Both feel odd to me having the operator inside the list.

My gut feeling is that `<<` could play poorly with types, but my gut was wrong about `..`

I'll toss up a PR that uses `...` after #99 merges.

**Comment by lloydmeta** [comment]
FWIW, I really like @Centril 's suggested `...` , as it's quite intuitive-looking.
