### ISSUE TITLE
HList maps and folds may not need an Index parameter

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#108]
Here's the result of my investigation so far:

Simply removing the `Index` param from `HMappable` results in conflicting impls, but these can be resolved by changing the impls for borrowed hlists a bit:

```rust
// old (requires Index param to resolve ambiguities)
impl HMappable<F>                    for HNil { ... }
impl HMappable<F>                    for HCons<H, Tail> { ... }
impl HMappable<HCons<F, MapperTail>> for HCons<H, Tail> { ... }
impl HMappable<F>                    for &'a HCons<H, HNil> { ... } <-- removed
impl HMappable<HCons<F, HNil>>       for &'a HCons<H, HNil> { ... } <-- removed
impl HMappable<F>                    for &'a HCons<H, Tail> { ... }
impl HMappable<HCons<F, MapperTail>> for &'a HCons<H, Tail> { ... }

// new (unambiguous)
impl HMappable<F>                    for HNil { ... }
impl HMappable<F>                    for HCons<H, Tail> { ... }
impl HMappable<HCons<F, MapperTail>> for HCons<H, Tail> { ... }
impl HMappable<F>                    for &'a HNil { ... }           <-- added
impl HMappable<F>                    for &'a HCons<H, Tail> { ... }
impl HMappable<HCons<F, MapperTail>> for &'a HCons<H, Tail> { ... }
```

Looking around, I see the other traits also don't have impls for `&'a HNil`, as if this was deliberately avoided for some reason.  I wonder why?  (maybe this was left over from some attempt to work around infinite recursion issues, which I recall tend to happen when dealing with impls on references?)

I'm still looking into the Foldable traits, which seem even more unusual; I'm not sure why there's an impl involving `&'a F`...

---

(**Edit:** Okay, there's good reason for the `&'a F`.  It can be fixed with the addition of a helper trait as an implementation detail (and then users will no longer need to borrow the closure when calling `foldr`), but it would also make the documentation a bit more frightening.  I'll hold off on suggesting this for now.)

**Comment by ExpHP** [comment]
Ah, rats. Right as I was about to submit a PR, a possible downside occurred to me. (though maybe it's no big deal)

Something which isn't so good about the existing by-value impls (and what I was going to change the by-ref impls to) is that they allow you to supply more functions than elements.

```rust
use frunk::prelude::*;

let list = hlist![3, "hello"]; // notice: only two elements!

// mapping by value
list.map(hlist![
    |x| println!("{}", x),
    |x| println!("{}", x),
    |x| println!("{}", x), // we are permitted to pass in more than two functions,
    |x| println!("{}", x), // even though we probably shouldn't be.
]);

// mapping by ref
list.as_ref().map(hlist![
    |x| println!("{}", x),
    |x| println!("{}", x),
    |x| println!("{}", x), // this is forbidden by the current impls on &HCons,
    |x| println!("{}", x), // but would be allowed after my changes
]);
```

But to be honest, I'm not sure how big of a deal this, because (a) I can't really imagine this situation ever occurring without at least one type error showing up somewhere else, and (b) it can't really be avoided. It seems like empty hlists *ought* to be mappable, and there's no way we'll ever be able to prevent `hlist![].map(hlist![f, g, h])` while still supporting `hlist![].map(|x: i32| x + 10)`.[1]

(but if we do want to double-down on length-checking, the `Index` parameter can still be removed; we just need to change the `HCons<H, Tail>` impls to `HCons<A, HCons<B, Tail>>`)

---

[1] that said, we *could* prevent `hlist![].map(hlist![f, g, h])` if single functions were forced to be wrapped in a newtype. I.e. `hlist![].map(Single(|x: i32| x + 10))`

**Comment by lloydmeta** [comment]
Aah, interesting; I forgot about the length checking, which I think helps to keep things neat (strict), but you do bring up a good point about empty Hlist already violating this to some degree.

My gut feeling is that it would be worth it to keep the length checking, even we have to go and implement on `HCons<A, HCons<B, Tail>>` instead of a `Tail` type param though.

Will give it a bit more thought :) Maybe @Centril can chime in with his opinion as well, for quorum :)
