### ISSUE TITLE
More effective use of semantic versioning

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#111]
What I've seen so far during my time contributing is that frunk takes a fairly relaxed attitude towards introducing breaking changes, yet it is only at version 0.1.36.

This makes me concerned that breaking changes are perhaps frequently published as patch number upgrades. This can cause breakage in downstream crates, because by default, `cargo` will gladly download a crate with a larger patch number than specified in Cargo.toml.

I think the next release should be v0.2.0. :slightly_smiling_face:

**Comment by lloydmeta** [comment]
Agreed with accusation and recommendation 👍

**Comment by Centril** [comment]
So; Given that we're all entirely in agreement; I'll go ahead and close this as resolved =P
