### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Centril** [lloydmeta/frunk#118]
@lloydmeta @ExpHP 

So... Anything left to do before releasing the next version?

**Comment by ExpHP** [comment]
無

**Comment by lloydmeta** [comment]
Agreed. One thing though, regarding versioning; how do we want to version the subprojects?

I think there have been quite a few non-backwards compatible changes in `core`, while `derives` haven't been touched, nor `laws` (I think?), but I'm somewhat inclined to say we should just go ahead and bump major versions for them.

If we do, should we just start clean and align all of them for cleanliness? For example 0.2.0 to match the main project? Or should each subproject just get bumped by one minor version (e.g. `core` goes to 0.1.0 from 0.0.23)

**Comment by Centril** [comment]
> while derives haven't been touched

👎 

> I'm somewhat inclined to say we should just go ahead and bump major versions for them.

👍 

> If we do, should we just start clean and align all of them for cleanliness?

👍

> Or should each subproject just get bumped by one minor versio

👎

**Comment by Centril** [comment]
Clarification: I feel that if frunk_core is bumped, then everything else should be bumped. derives have to be bumped because core has been since core is a dependency of more or less everything. Bumping everything is also more risk free.

Btw... We should start keeping a CHANGELOG.md after this version.

**Comment by lloydmeta** [comment]
So to be clear, are we ok with raising everything to `0.2.0` ? 

> Btw... We should start keeping a CHANGELOG.md after this version.

:+1:

**Comment by ExpHP** [comment]
:+1:

**Comment by lloydmeta** [comment]
Published ! 

I'm thinking of tweeting a ... tweet to announce this and wanted to shout out to both of you. I found @Centril's twitter handle, do you have one as well @ExpHP ? 

No worries / pressure at all if you don't want to be mentioned, just let me know :)

**Comment by Centril** [comment]
Maybe announce on Reddit / users.rust-lang.org? 😁

**Comment by ExpHP** [comment]
Yep, I don't have a Twitter account. If you're tweeting you can just mention me without the @.

**Comment by lloydmeta** [comment]
> Maybe announce (the new version) on Reddit / users.rust-lang.org? 😁

I'm scared of Reddit, but the users forum sounds good :)

> Yep, I don't have a Twitter account. If you're tweeting you can just mention me without the @.

Understood !
