### ISSUE TITLE
Add Selector::get_mut

### ISSUE THREAD

**Issue by jesskfullwood** [lloydmeta/frunk#129]
Thanks for the cool lib, I'm using it heavily to create a typesafe dataframe-like lib. 

I have a need for a `get_mut` function on the `Selector` trait. Is there a reason this is missing/would you accept a PR?

**Comment by lloydmeta** [comment]
Hey there, thanks for reaching out :) No, as far as I can tell there is no reason why it's missing; a PR implementing it is definitely welcome :)

**Comment by ExpHP** [comment]
I am not at all opposed, in fact I was wondering myself why it wasn't there when I first saw the crate.

**Comment by Centril** [comment]
If you can make it work, I'd also welcome a PR. :)
