### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by skade** [lloydmeta/frunk#14]
Concerning this: https://github.com/lloydmeta/frunk#benchmarks

You can use cargo support for benchmarks to circumvent this solution.

1. Create a folder called `benches/`
2. Put your benchmarks inside as files
3. Run them with `cargo bench`. Which obviously only works on nightly, but, well, just call it using nightly toolchains then :).

**Comment by lloydmeta** [comment]
Thanks for that tip ! Done :)
