### ISSUE TITLE
Is there a way to map enum -> coprod in-place?

### ISSUE THREAD

**Issue by Hirrolot** [lloydmeta/frunk#165]
I have an enumeration from a third-party crate, I want to map it to a coproduct in-place. So basically I need to match it, but it's a lot of boilerplate, isn't it? Is there a solution?

**Comment by ExpHP** [comment]
What do you mean by in-place?  Normally I take that to mean "without copying data", but Coproducts and `enum`s have different layouts so copying is required.

Without knowing the full details of your problem, the boilerplatey-ness of conversion of any type into a frunk type is usually best handled by leveraging `derive(Generic)` or `derive(LabelledGeneric)` in some way.  Of course, you cannot do this directly for a type in an external crate, but you can define a similar looking type in your crate and derive the traits on that.  This is still boilerplate, but hopefully not as much.  (Macros can help, too).

**Comment by Hirrolot** [comment]
By "in-place" I mean that given a variable `foo` of an enumeration type in a third-party crate, convert it to a coproduct representation. Are there macros for it?

**Comment by ExpHP** [comment]
A macro can only generate code based on the input tokens provided to it.  There is no form of reflection or type system access that could allow it to discover what the variants of an enum are called (or what they contain) without all of this information being provided directly to the macro.

So, no matter what, your crate will *at bare minimum* need to contain some sort of listing of all of the variants of this enum and all of their fields.  (ideally, this may just mean copying and pasting the enum definition from the external crate.  After that, the general idea is to put `#[attribute]`-style macros on it or place it inside some `my_autoderiving_macro!` call to generate all the rest of the boilerplate you need.)

**Comment by Hirrolot** [comment]
Ok, thank you for the help, just expected that someone has already written a macro like this:

```rust
enum Foo {
    A(i32),
    B(String),
}

type MyCoprodType = Coprod!(i32, Foo);

fn main() {
    let foo: MyCoprodType = magic_macro!(Foo, (A: i32), (B: String), Foo::A(123));
    assert_eq!(foo, MyCoprodType::inject(123));
}
```
