### ISSUE TITLE
Edition

### ISSUE THREAD

**Issue by ImmemorConsultrixContrarie** [lloydmeta/frunk#182]
Rust will soon hit 2021 edition, but `frunk` is still at 2015 (which I found accidentally by trying to write `use` in tests).
Any thoughts about migration?

**Comment by lloydmeta** [comment]
++ I think it would make sense to migrate to at least 2018, if not 2021.

**Comment by ExpHP** [comment]
There was some discussion here: https://github.com/lloydmeta/frunk/pull/154#issuecomment-475841031

It's obviously a good idea, I'd say the only reason we haven't really was due to some accidents of timing.
