### ISSUE TITLE
Drop proc-macro-hack, upgrade syn to 2

### ISSUE THREAD

**Issue by CobaltCause** [lloydmeta/frunk#213]
* `proc-macro-hack` is deprecated since it's not needed in newer versions of Rust
  * See the note at the top of its [docs.rs page](https://docs.rs/proc-macro-hack/0.5.20+deprecated/proc_macro_hack/index.html)
  * If `frunk` *does* want to support the versions `proc-macro-hack` is needed for, this can be ignored
* `syn` 2 has been released
  * Upgrading would be nice so that users can compile less versions of `syn`

If the maintainers are interested in either or both of these changes, I can try to PR it, just thought I'd ask to gauge interest first.

**Comment by ExpHP** [comment]
Frunk is already using 2021 edition which was added in rust 1.56, so the MSRV (which I don't think we've invested much effort into tracking for frunk) is already beyond the versions that need proc-macro-hack (1.45) or syn 1 (1.50).

I would support both changes.

**Comment by CobaltCause** [comment]
> Frunk is already using 2021 edition

Oh lol. PR opened: #214.
