### ISSUE TITLE
The correct way of adding the crate frunk dependency

### ISSUE THREAD

**Issue by dima-starosud** [lloydmeta/frunk#218]
Most likely the issue is related to possibly outdated documentation.

Using `rustc 1.70.0 (90c541806 2023-05-31)` and following the latest docs here https://docs.rs/frunk/latest/frunk/ 
I've added `frunk = "0.4.2"` to the `Cargo.toml`, but the following code fails to compile:

    use frunk::prelude::*;
    use frunk::LabelledGeneric;

    #[derive(LabelledGeneric)]
    struct Zho {}

with the error:

    error[E0433]: failed to resolve: could not find `frunk_core` in the list of imported crates
     --> src/main.rs:4:10
      |
    4 | #[derive(LabelledGeneric)]
      |          ^^^^^^^^^^^^^^^ could not find `frunk_core` in the list of imported crates
      |
      = note: this error originates in the derive macro `LabelledGeneric` (in Nightly builds, run with -Z macro-backtrace for more info)

Adding `frunk_core = "0.4.2"` to the `Cargo.toml` fixes the issue, but I am not sure that's the proper way. Also, I couldn't find anything in the documentation about this.

To me it looks like sole `frunk = "0.4.2"` should work out of the box.

**Comment by lloydmeta** [comment]
I think you'll need to pull in frunk_core, unfortunately in order for the derive to work, since it's referenced in the macro that builds the derives.

https://github.com/lloydmeta/frunk/blob/34ba13d8162d276b50dfcb8a6c46d4445c2409a5/derives/src/derive_labelled_generic.rs#L107

**Comment by dima-starosud** [comment]
Thank you for the response 👍 
Do you think we should put this in the doc? i.e. deriving `Generic`/`LabelledGeneric` is probably the first prerequisite to use the lib, and to do that one should always pull `frunk_core`, but docs don't say anything about this.

**Comment by lloydmeta** [comment]
> Thank you for the response 👍 Do you think we should put this in the doc? i.e. deriving `Generic`/`LabelledGeneric` is probably the first prerequisite to use the lib, and to do that one should always pull `frunk_core`, but docs don't say anything about this.

That sounds good to me !

**Comment by lloydmeta** [comment]
Yeah, sounds good to me.

**Comment by dima-starosud** [comment]
I am not sure I am able to assign this ticket to me 🤔

**Comment by dima-starosud** [comment]
@lloydmeta Created PR for this https://github.com/lloydmeta/frunk/pull/219

**Comment by dima-starosud** [comment]
Thank you! That was fast 😃
