### ISSUE TITLE
`Validated`/`no_std`: replace `std::Vec` dependency with `alloc::Vec`

### ISSUE THREAD

**Issue by mammothbane** [lloydmeta/frunk#220]
Would you be open to a PR to conditionally replace the use of `std::Vec` in `frunk::Validated` with `alloc::Vec`? At a quick glance, I believe this is the only required change to make the whole project work in `no_std`-but-`alloc` environments.

**Comment by ExpHP** [comment]
Does it need to be conditional?  I'm not familiar with usage of or best practices involving the alloc crate, but I would suspect that if it is possible to always use alloc over std when possible then that would be preferred.

**Comment by ExpHP** [comment]
Oh yeah, I just remembered we have this:

```rust
#[cfg(not(feature = "std"))]
extern crate core as std;
```

Not 100% sure but I think that's a relic from a time back when you couldn't use `core::` without `no_std`??  These days you can use `core::` from any crate and that's what I think we ought to be doing for the things that don't require `std`.
