### ISSUE TITLE
HList should be a Semigroup

### ISSUE THREAD

**Issue by tupshin** [lloydmeta/frunk#26]
Inspired by https://gist.github.com/davidhoyt/5a759989122423d5674e 
If all of the elements of a HList are themselves Semigroups/Add, then we should be able to recursively combine the the two Semigroups.

Opening this ticket because I was dabbling in it. Looks like it might be possible, but adds a lot of type annotation weight, at a minimum.

**Comment by lloydmeta** [comment]
This sounds like a good idea :) 

I'm definitely interested to see what a working version might look like !

**Comment by tupshin** [comment]
See pull request

**Comment by lloydmeta** [comment]
Closed via #28
