### ISSUE TITLE
hlist as a type to be declared

### ISSUE THREAD

**Issue by AnirudhVyas** [lloydmeta/frunk#50]
```Rust
struct Row<F> {
    fields: HCons<F, HNil>,
    tags: HashSet<MetaTag>
}
```
I have declared an HList like this - is this right notation? I am rust newbie and I am attempting to translate some of the things i love in scala here. Note that field (F in this case) is my own impl for a trait that may be type bound later - with a generic type parameter T - row attempts to start with head field as a seed field. Due to lack of documentation I wanted to ask this here ... please let me know if you already have documentation describing this.

**Comment by AnirudhVyas** [comment]
Here are my data structures in a nutshell ... please call out - if I am abusing anything, as I am reading and doing things at the moment.
```Rust
struct MetaTag {
    name: String,
    value: String,
    description: String
}

// A column for structured data.
#[allow(dead_code)]
struct Field<T> {
    name: String,
    value: T,
}

#[allow(dead_code)]
struct Row<F> {
    fields: HCons<F, HNil>,
    tags: HashSet<MetaTag>
}
// A block that can be used for writing set of rows to a source to be read from.
struct Block<R> {
    rows: HCons<R, HNil>
}

```

**Comment by lloydmeta** [comment]
Hi there,

Always nice to see another Scalaist trying out Rust. I'm also quite a noobie :)

In your example, am I right in assuming that the `fields` in `Row` can contain more than 1 field? As in, you want the HList to possibly contain more than 1 `Field`?

If so, I think you want something like this

```rust
struct Row<FHead, FTail> {
    fields: HCons<FHead, FTail>,
    tags: HashSet<MetaTag>
}
```

**Comment by AnirudhVyas** [comment]
fantastic ... good point yep thats right! appreciate your help!
