### ISSUE TITLE
HList::length does not need to take a self parameter

### ISSUE THREAD

**Issue by Marwes** [lloydmeta/frunk#59]
Looked into porting the HList I use in [gluon](https://github.com/gluon-lang/gluon/blob/59aeab59a259c78beb4ffeac2e6c6bb9048f11fa/vm/src/api/mod.rs#L1301) to the hlist in this crate. While I could port it there is a slight drawback in that the `HList::length` function in frunk requires a `&self` parameter which is not actually necessary. Could this perhaps be removed? (Also, should it perhaps be named `len` to mirror `Vec`, `HashMap` etc ?)

**Comment by lloydmeta** [comment]
You raise a very good point; given that we know the length at compile time, there is no need for the `&self` parameter, as that information is already known from the type. Also, the naming is terrible: that most definitely should be changed to `len`. While we're here, the return type should also be changed to return `usize` for consistency with `Vec`.

That said, if we change it to not accept a `&self` parameter, wouldn't that mean that we lose the ability to call it on a value, in the same way we do on `Vec`? e.g.

```rust
let h = hlist![9000, "joe", 41f32];

// can't do this any more
h.len();

// need to do this:
<Hlist![usize, &str, f32] as HList>::len();
// or if we have a generic T HList:
<T as HList>::len();
```

Even though unnecessary, it might be more ergonomic to go with the version that uses `&self`? I don't really have a strong opinion on this, btw, just thinking aloud.

**Comment by Marwes** [comment]
Why not both then? The self `len` could be a default implementation which calls the static version.

**Comment by lloydmeta** [comment]
Perfect. I like that idea. One hiccup though is we don't have overloading so there needs to be 2 different names.

What do you think of something like this? 

```rust

    fn len() -> usize; // static one that we define

    fn length(&self) -> usize { <Self as HList>::len() } // forwarder to the static one.
```

**Comment by Marwes** [comment]
Probably more consistent with conventions to make the `&self` variant `len`. I feel like `length` kinda makes me think it may return something different than `len` so maybe make the non-self variant `static_len`? Just something that involves just the `len` shortening.

**Comment by lloydmeta** [comment]
@Marwes sounds reasonable to me. Opened #60 to add `static_len` (usage [here](https://github.com/lloydmeta/frunk/commit/d41b3d4b4829a22a44e18692962bec49aff6a326#diff-46450dcdc1a0c47051b3d48acc0f01fbR1036)) and other renamings / retypings.
