### ISSUE TITLE
Allow mapping a single function over an HList of types it can handle.

### ISSUE THREAD

**Issue by remexre** [lloydmeta/frunk#68]
Use-case: https://github.com/oftlisp/oftlisp-rs/blob/231649e3d6b00827526eb612e9be760d60ebf502/src/interpreter/primitives.rs

**Comment by lloydmeta** [comment]
Hey there,

That sounds like a great idea, not to mention you have a cool usecase :)

Would you like to take a stab at implementing it?

**Comment by remexre** [comment]
[I tried adding it last night](https://github.com/lloydmeta/frunk/compare/master...remexre:f4e3613), but it runs into issues with monomorphization -- if I pass it a `Fn<T, U>(SomeAccType, Field<T, U>) -> (&'static str, U)`, it generates a single function for the first item in the `HList` (e.g. `Field<(c, a, r), C::BuiltinFunction>`), which then rejects the remainder of the list.

Another workaround would be to add a method to get an `HCons<Field<(), T>, ...>` directly on the `LabelledGeneric` trait, although this is clearly less elegant.

**Comment by lloydmeta** [comment]
>  runs into issues with monomorphization

Ahh yes, now I recall running into the same problem when I last tried to do this. It works if all the types in the HList are the same, but it isn't as useful. I wonder if we can somehow make the compiler delay monomorphisation until the whole trait-implementation-recursion stuff is done?

> Another workaround would be to add a method to get an HCons<Field<(), T>, ...> (with no type-level field name) directly on the LabelledGeneric trait, although this is clearly less elegant.

There is something similar, namely a `into_unlabelled()` method that can turn something that's labelled into something unlabelled, (so ` HCons<T, ...>`), but I'm not sure if that helps?

**Comment by remexre** [comment]
> It works if all the types in the HList are the same, but it isn't as useful.

Maybe it's possible to do something if all the values are members of the same trait? I can't figure out a way to do it in this case, though.

> There is something similar, namely a `into_unlabelled()` method that can turn something that's labelled into something unlabelled, (so `HCons<T, ...>`), but I'm not sure if that helps?

No, I'm trying to generate a hashmap from the struct, so I need the field names as keys...

**Comment by lloydmeta** [comment]
I see. It's not that hard to do something that will strip the type-level names but still hold onto the value-level names, and we can maybe use another struct for that purpose, such as `ValueField`;

```rust
pub struct ValueField<Type> {
    pub name: &'static str,
    pub value: Type,
}

/// A trait that strips type-level strings from the labels
pub trait IntoValueLabelled {
    type Output;
    fn into_value_labelled(self) -> Self::Output;
}

impl IntoValueLabelled for HNil {
    type Output = HNil;
    fn into_value_labelled(self) -> Self::Output {
        self
    }
}

impl<Label, Value, Tail> IntoValueLabelled for HCons<Field<Label, Value>, Tail>
where
    Tail: IntoValueLabelled,
{
    type Output = HCons<ValueField<Value>, <Tail as IntoValueLabelled>::Output>;

    fn into_value_labelled(self) -> Self::Output {
        HCons {
            head: ValueField { name: self.head.name, value: self.head.value },
            tail: self.tail.into_value_labelled(),
        }
    }
}
```

I think the problem is though, that at the end of the day, you'd still have different-typed elements in your HList, if the original HList was heterogeneous.

```rust
#[test]
    fn test_value_labelling() {
        let labelled_hlist = hlist![field!(name, "joe"), field!((a, g, e), 3)];
       // See here, we still have &str and isize
        let value_labelled: Hlist![ValueField<&str>, ValueField<isize>] = labelled_hlist.into_value_labelled();
        let hlist_pat!(f1, f2) = value_labelled;
       // The names are retained though.
        assert_eq!(f1.name, "name");
        assert_eq!(f2.name, "age");
    }
```

**Comment by remexre** [comment]
That'd work great for my specific case, although I agree that a more general solution would be better.

**Comment by lloydmeta** [comment]
I've opened #69 to add such a trait, but I'm not sure how it solves our monomorphisation problem?

**Comment by remexre** [comment]
In my use-case, I'm turning the struct into a HashMap, so if all the keys *aren't* the same type, that should be an error.

**Comment by lloydmeta** [comment]
Ah, I see. That makes sense. In which case, merging that PR and adding what you've got going with regards to single-function folding _should_ allow you to move forward?

**Comment by remexre** [comment]
I think so, but there's no rush, if you think it's possible to make a more general solution; I've got a macro solution that works (even if I'd prefer the generality of the LabelledGeneric).

**Comment by lloydmeta** [comment]
I think both of the features discussed (single-function mapping/folding of HLists, and stripping type-level names) are generally useful anyways, and they are small enough to be used in combination with other features to do more useful work; e.g. in your case.

I'm going to go ahead and merge #69. If you'd like to send a PR to implement the single-function piece, you're more than welcome. If not, I can do it, just let me know :)

**Comment by lloydmeta** [comment]
I've just released new versions of the main lib based on core 0.0.20 that has the 2 pieces of functionality we discussed.
