### ISSUE TITLE
Moving `Coproduct` (and associated traits) to `frunk_core`

### ISSUE THREAD

**Issue by Centril** [lloydmeta/frunk#77]
Having `Coproduct` in `frunk_core` could let you derive enums in the future lets dependencies of `frunk_core` get access to `Coproduct` without having to pay for a dependency on `syn` in `frunk_derive`... I think this makes frunk_core more appetizing as a dependency. What do you think?

**Comment by lloydmeta** [comment]
Ohh, that's a good point, your reasoning makes a lot of sense :)

I think going forward, that's a pretty good rule of thumb too, for deciding where to put things ..

A PR would be more than welcome !

**Comment by Centril** [comment]
Sweet! I'll fix one up in a bit  =)
