### ISSUE TITLE
Splitting coproducts, and upcasting to larger coproducts

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#86]
Over the weekend I've been working on a [reimplementation of frunk](https://github.com/ExpHP/funky/tree/master) to help understand the current design and gather ideas.  The following two ideas are *really low hanging fruit;* I mean, when I wrote them, I just figured that frunk _obviously_ must already have something like these (but looking around, I don't think it does).

I can add something similar to frunk if others would like them.

---

#### Splitting coproducts

Split e.g. `Coprod![A, B, C, D, E]` into `Result<Coprod![D, A, B], Coprod![C, E]>`.

(In my repo I named it `sculpt` after the similar operation on HLists, but I'm not too sure about that name)

```rust
// Indices is usually inferred
pub trait CoprodSculptor<Targets, Indices>: Sized {
    type Remainder;

    fn sculpt(self) -> Result<Targets, Self::Remainder>;
}
```

The [implementation](https://github.com/ExpHP/funky/blob/e475f7844e124bb7e02c2b38967e2b6aa5e373d1/src/coprod.rs#L528-L565) is just repeated calls to `uninject()`. (`.pluck()` in my codebase)

#### Upcasting

Upcast e.g. `Coprod![A, B, D]` into `Coprod![A, B, C, D, E]`.

```rust
// Indices is usually inferred
pub trait CoprodEmbedder<Choices, Indices> {
    fn embed(self) -> Choices;
}
```

My [implementation of `embed`](https://github.com/ExpHP/funky/blob/e475f7844e124bb7e02c2b38967e2b6aa5e373d1/src/coprod.rs#L633-L654) is insultingly simple, and if rust had generic closures it could be written as just `coprod.fold(|x| Target::inject(x))`.  Some neat properties that fall out of this simple implementation are that order doesn't matter, and duplicate types in the input can map to the same place in the output (so `Coprod![C, A, E]` and `Coprod![B, B, B, B]` can also be converted into `Coprod![A, B, C, D, E]`).

---

**Note:**  `embed` seems like it *could* be just a special case of `sculpt` where `Remainder = CNil`.  But I am not certain. In my current implementation, the two methods have very different implementations and the indices take on completely different representations (indicated by the use of the newtype wrapper [`PopSeq`](https://github.com/ExpHP/funky/blob/e475f7844e124bb7e02c2b38967e2b6aa5e373d1/src/hlist.rs#L464-L476) that wraps the indices [in implementations of `sculpt`](https://github.com/ExpHP/funky/blob/e475f7844e124bb7e02c2b38967e2b6aa5e373d1/src/coprod.rs#L529)).

**Comment by lloydmeta** [comment]
+ 💯  on adding splitting and upcasting functions :)

I think we can keep `embed` and `sculpt` separate; I agree with you regarding the differences in implementation and indices. IMHO, there's no need at this point to try to consolidate those them :)
