### ISSUE TITLE
Mapping coproducts

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#92]
I discovered there was no `map` for coproducts when writing the docs for `CoprodEmbedder`, where I mention what happens if there are duplicate types in the input (which is something that typically only ever really happens as the result of mapping, so I couldn't come up with a palatable code example).

`map` for coproducts should probably have all of the same features as the one on HLists:

* Mapping with an `hlist![]` of `FnOnce`s or a single `FnOnce`
* Support for mapping by reference.
* Anything else I missed

I think I'll get to this at some point after implementing the ergonomics hacks in #90.

**Comment by Centril** [comment]
Nice 👍

**Comment by BGR360** [comment]
Didn't notice this issue when I posted mine, but I implemented this in https://github.com/lloydmeta/frunk/pull/204!
