### ISSUE TITLE
CNil::absurd() for producing any type

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#93]
Dangit, I'm having too many ideas all at once now!

```rust
impl CNil {
    pub fn absurd<T>(self) -> T {
        match self { }
    }
}
```

Bikeshedding for the name is welcome.  The name `absurd()` comes from proof solvers.  Picture it appearing e.g. at the bottom of [this example](https://github.com/lloydmeta/frunk/blob/6917e5806dc9ccdb408e493e0a4e18e02b1ad71a/core/src/coproduct.rs#L494-L510), or as the body of [this impl](https://github.com/lloydmeta/frunk/blob/6917e5806dc9ccdb408e493e0a4e18e02b1ad71a/core/src/coproduct.rs#L338-L344). (random aside: uh... why is that impl `#[doc(hidden)]`?)

**Comment by Centril** [comment]
Hmm; Rather than doing this (and since we introduced some other breaking changes in master), I'd like us to get rid of `CNil` and simply use `!` (assuming we can do it wrt. coherence, which I think we can), this is what the standard library has been doing as of late, and the hope is that `!` should be the only uninhabited type in the entire ecosystem.

I'd personally like to have:

```rust
#[lang_item = "never"]
impl ! {
    pub fn absurd<T>(self) -> T {
        match self {}
    }
}
```
in the standard library tho.

**Comment by ExpHP** [comment]
Okay.  Do note that this will prevent inherent method wrappers on empty coproducts; that said, in most cases not having these methods is not a huge loss (most have no implementations for CNil, and who needs to take a `subset()` of a coproduct that is monomorphically known to be empty?), but rather, it's just one of those places where the ergonomical abstraction will "leak."

**Comment by Centril** [comment]
> Okay. Do note that this will prevent inherent method wrappers (#90) on empty coproducts. That said, in most cases not having these methods is not a huge loss [..]

Yeah sounds fine ^,-

**Comment by ExpHP** [comment]
Do you mean that not having the wrappers on CNil sounds fine? Or that keeping CNil around sounds fine?

**Comment by Centril** [comment]
Sorry, I meant the former.

**Comment by ExpHP** [comment]
Okay, I'll close this for now.
