### ISSUE TITLE
(C-SERDE) the serde feature should be named "serde"

### ISSUE THREAD

**Issue by ExpHP** [lloydmeta/frunk#97]
See [C-SERDE](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde) in the Rust API guidelines

Note it is not actually possible to name a feature the same as a dependency. Rather, [`serde` provides a `"derive"` feature](https://github.com/serde-rs/serde/blob/7ad836e6a97d7cc08cb36bc962745f3262208f66/serde/src/lib.rs#L238-L276) specifically for this purpose.

**Comment by lloydmeta** [comment]
Oh interesting; I didn't know about these guidelines. Definitely a good idea to follow the convention.

For the sake of being tiringly explicit, it looks like we need to:

1. Put the `serde` dependency [behind a `derive` feature](https://github.com/serde-rs/serde/blob/7ad836e6a97d7cc08cb36bc962745f3262208f66/serde/src/lib.rs#L264)
2. Use [`serde` as a feature flag](https://github.com/serde-rs/serde/blob/7ad836e6a97d7cc08cb36bc962745f3262208f66/serde/src/lib.rs#L271).

I wonder if we should add mention this in the README as well.

**Comment by ExpHP** [comment]
Nah, you just remove `serde_derive` as a dependency, and enable the `derive` feature on your serde dependency.  (and don't set up any feature explicitly for serde)

If you do this, then the only feature exposed by frunk will be called serde (it will be the feature autogenerated by cargo because serde is an optional dep)

**Comment by lloydmeta** [comment]
> If you do this, then the only feature exposed by frunk will be called serde (it will be the feature autogenerated by cargo because serde is an optional dep)

Oh nice; didn't know this was possible 😎
